# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

services:
  - mysql

php:
    - 5.6
    - 7.0
before_script:
    - composer install
    - mysql -u root -e 'CREATE DATABASE testbase;'
script: phpunit

notifications:
    email:
        - munizeverton@gmail.com